services:
  infodotgamedb:
    image: mariadb
    restart: unless-stopped
    container_name: infodotgamedb
    ports:
      - "3315:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - infodotgame_db:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d
    networks:
      - infodotgame_network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - ${MAILPIT_HTTP_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025

volumes:
  infodotgame_db:

networks:
  infodotgame_network:
    external: true
    name: infodotgame_network
